from langchain_core.prompts import ChatPromptTemplate
from langchain_google_genai import ChatGoogleGenerativeAI
llm = ChatGoogleGenerativeAI(model="gemini-2.5-flash")

async def create_draft(content_description: str, initial_content: str) -> str:

    system = (
        "You are an assistant that refines and improves content generated by another LLM. "
        "Your task is to enhance the provided Markdown content by removing any unnecessary text, improving the structure, and adding more detailed content if needed. "
        "Use the content description as a guide to ensure the content aligns with the user's requirements."
    )

    human = "Refine and improve the following Markdown content based on the given content description. Ensure the final content is detailed, well-structured, and free of unnecessary text:\n\nContent Description:\n{description}\n\nInitial Content:\n{content}"
    
    prompt = ChatPromptTemplate.from_messages([("system", system), ("human", human)])
    chain = prompt |llm 
    response = chain.invoke({"description": content_description, "content": initial_content})
    refined_content = response.content.strip()

    return refined_content